<a href="https://colab.research.google.com/github/vpattangi/emoji-reddit-data-cleaning/blob/main/emoji_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Emoji Use In Online Discourse

This project investigates how emojis, specifically the skull (💀) and loudly crying face (😭), function as linguistic markers of emotional intensity in digital communication.

Using a large-scale dataset of Reddit comments (May 2019), this study analyzes over one million entries to explore how emoji usage varies across different online communities, including sports, gaming, memes, and political discussions.

The project focuses on identifying patterns such as:
- Repeated emoji usage as a form of emotional amplification
- Differences between informal (emoji-rich) and formal (emoji-free) communication
- The relationship between topic context and expressive language

By combining quantitative data analysis with linguistic theory, this study highlights how modern online discourse blends text and visual symbols to convey tone, humor, and exaggerated emotion.

## Cleaning The Dataset

####Load Dataset

In [33]:
import pandas as pd

df = pd.read_csv("/content/kaggle_RC_2019-05.csv")
df.head()

,subreddit,body,controversiality,score
0,gameofthrones,Your submission has been automatically removed...,0,1
1,aww,"Dont squeeze her with you massive hand, you me...",0,19
2,gaming,It's pretty well known and it was a paid produ...,0,3
3,news,You know we have laws against that currently c...,0,10
4,politics,"Yes, there is a difference between gentle supp...",0,1

####Filter for emojis

In [34]:
filtered = df[df["body"].str.contains("💀|😭", na=False)]
filtered.head()

,subreddit,body,controversiality,score
5123,AskReddit,"Beading. \n\nWatching my pet chickens, when I ...",0,1
5232,FortNiteBR,Lmao 💀💀 y’all some funny bulls,0,2
5248,funny,"So technically apps that have ""lite"" ar the en...",0,3
6918,RoastMe,🙌🖕💀 go to hell with ur kleenexs too,0,-1
8806,gameofthrones,Skyrim is probably the closest we’re gonna get...,0,2

####Save Cleaned Dataset

In [35]:
filtered.to_csv("cleaned_emoji_data.csv", index=False)

####Download Cleaned Dataset

In [36]:
files.download("cleaned_emoji_data.csv")

## Reddit Category Classification

To better understand how language and emoji usage vary across different types of online communities, each Reddit comment is categorized based on its subreddit.

Subreddits are grouped into broader thematic categories, including:
- Sports (e.g., NBA, NFL)
- Gaming (e.g., Fortnite, Minecraft)
- Memes/Humor
- Politics/News
- Other

This classification allows the dataset to be analyzed at a higher level, making it possible to compare how different communities communicate.

For example, meme and gaming communities are expected to use more emojis and exaggerated expressions, while political and news-related discussions tend to be more formal and emoji-free.

By organizing the data into categories, this step enables both quantitative analysis (e.g., frequency of emoji use) and qualitative insights into how tone and emotional expression differ across contexts.

####Load Cleaned Dataset

In [37]:
import pandas as pd

df = pd.read_csv("cleaned_emoji_data.csv")
df.head()

,subreddit,body,controversiality,score
0,AskReddit,"Beading. \n\nWatching my pet chickens, when I ...",0,1
1,FortNiteBR,Lmao 💀💀 y’all some funny bulls,0,2
2,funny,"So technically apps that have ""lite"" ar the en...",0,3
3,RoastMe,🙌🖕💀 go to hell with ur kleenexs too,0,-1
4,gameofthrones,Skyrim is probably the closest we’re gonna get...,0,2

#### Creating Subreddit Categories

In [38]:
def categorize_topic(subreddit):
    subreddit = str(subreddit).lower()

    # sports
    if any(word in subreddit for word in ["nba", "nfl", "soccer", "sports", "baseball"]):
        return "sports"

    # gaming
    elif any(word in subreddit for word in ["gaming", "fortnite", "apex", "cod", "minecraft"]):
        return "gaming"

    # memes / humor
    elif any(word in subreddit for word in ["funny", "memes", "dankmemes"]):
        return "memes"

    # politics / serious
    elif any(word in subreddit for word in ["politics", "news", "worldnews"]):
        return "politics"

    else:
        return "other"

#### Apply Category Sorting to Dataset

In [39]:
df["topic"] = df["subreddit"].apply(categorize_topic)

df.head()

,subreddit,body,controversiality,score,topic
0,AskReddit,"Beading. \n\nWatching my pet chickens, when I ...",0,1,other
1,FortNiteBR,Lmao 💀💀 y’all some funny bulls,0,2,gaming
2,funny,"So technically apps that have ""lite"" ar the en...",0,3,memes
3,RoastMe,🙌🖕💀 go to hell with ur kleenexs too,0,-1,other
4,gameofthrones,Skyrim is probably the closest we’re gonna get...,0,2,other

#### Lines Per Category Count

In [40]:
df["topic"].value_counts()

topic
other       388
gaming       52
memes        42
sports       18
politics      4
Name: count, dtype: int64

#### Compare Emoji Usage by Topic

In [41]:
def get_emoji_type(text):
    if pd.isna(text):
        return "none"
    has_skull = "💀" in text
    has_cry = "😭" in text

    if has_skull and has_cry:
        return "mixed"
    elif has_skull:
        return "skull"
    elif has_cry:
        return "crying"
    else:
        return "none"

df["emoji_type"] = df["body"].apply(get_emoji_type)

In [42]:
pd.crosstab(df["topic"], df["emoji_type"])

emoji_type  crying  mixed  skull
topic
gaming          45      1      6
memes           38      0      4
other          352      0     36
politics         4      0      0
sports          12      0      6

#### Examples Per Topic

In [43]:
df[df["topic"] == "sports"].head(5)
df[df["topic"] == "gaming"].head(5)
df[df["topic"] == "memes"].head(5)

,subreddit,body,controversiality,score,topic,emoji_type
2,funny,"So technically apps that have ""lite"" ar the en...",0,3,memes,crying
6,funny,That's an ugly fucking kid tho I'm dead 😭,0,1,memes,crying
10,memes,If only this were true and we could actually m...,0,3,memes,crying
30,memes,RIP unsettled Tom he will always be remembered 😭😭,0,7,memes,crying
34,funny,"&gt;...but how could a shoe, talk to you, the ...",0,2,memes,crying

#### Save Final Dataset

In [44]:
df.to_csv("final_emoji_topic_dataset.csv", index=False)

##Emoji Intensification Classification

Emoji intensification is defined as the repetition of emojis within a single comment to amplify emotional meaning.

This functions as a paralinguistic feature of digital language, where repeated symbols (e.g., 💀💀💀, 😭😭😭) enhance the perceived intensity of an expression beyond what text alone conveys.

In this analysis, comments are categorized into:
- Single emoji use (casual expression)
- Repeated emoji use (intensified emotion)

This distinction allows for a more nuanced understanding of how emotional emphasis is constructed in online communication.

#### Emoji Intensification Identification

In [45]:
import pandas as pd
import re

# load dataset
df = pd.read_csv("cleaned_emoji_data.csv")

# detect repeated emojis
def has_repeated_emoji(text):
    if pd.isna(text):
        return False
    return bool(re.search(r'(💀){2,}|(😭){2,}', text))

# filter
intensified_comments = df[df["body"].apply(has_repeated_emoji)]

# print results
print("Emoji Intensification Comments:")
for i, row in intensified_comments.iterrows():
    print(f"Subreddit: {row['subreddit']}")
    print(f"Comment: {row['body']}")
    print("-" * 50)

# save to CSV
intensified_comments.to_csv("emoji_intensification.csv", index=False)

print("\nSaved to emoji_intensification.csv")

Emoji Intensification Comments:
Subreddit: FortNiteBR
Comment: Lmao 💀💀 y’all some funny bulls
--------------------------------------------------
Subreddit: gameofthrones
Comment: Skyrim is probably the closest we’re gonna get for a while 😭😭
--------------------------------------------------
Subreddit: FortNiteBR
Comment: I WANT DREAM FEET 😭😭
--------------------------------------------------
Subreddit: freefolk
Comment: Yeah. I never liked Theon. Never gave a shit. Then just watching him kill like 25 dudes alone. The heart it takes to be the last man standing in the position and he has 6 friggin fingers. Then crows nest over there tipped me over with the “...you’re a good man.” Ugh🥺🥺😭😭
--------------------------------------------------
Subreddit: nba
Comment: Imagine being a bucks fan and really thinking Giannis is the best player in the world 💀💀💀💀💀
--------------------------------------------------
Subreddit: memes
Comment: If only this were true and we could actually make stan lee 😭😭😭
--------------------------------------------------
Subreddit: FortNiteBR
Comment: Lmaaooo 💀💀 why? Sole nah
--------------------------------------------------
Subreddit: teenagers
Comment: And most sad of all, my god roll weapons in destiny 2 😭😭😭😭
--------------------------------------------------
Subreddit: teenagers
Comment: I was gonna watch it this Saturday but I have choir practice at 1:30 and the earliest showing is 10:30. Now my Uncle's gonna take only my brother's and they'll try to spoil it 😭😭😭
--------------------------------------------------
Subreddit: memes
Comment: RIP unsettled Tom he will always be remembered 😭😭
--------------------------------------------------
Subreddit: aww
Comment: Aww lucky doggie and family! Too heartwarming 😭😭😭
--------------------------------------------------
Subreddit: AskReddit
Comment: I kinda want a cheeseburger 😭😭😭😭😭
--------------------------------------------------
Subreddit: RoastMe
Comment: Hey! Wow! I love your look! How would you like to model as a musician in an ad for my app? I can’t pay you but it’s gonna be big big big and you’ll get so much exposure! Dm me for deets!! 🥳🥳😁😁😭😭
--------------------------------------------------
Subreddit: memes
Comment: Everything except for YT is blocked in my school 😭😭 but I use VPN👍👍
--------------------------------------------------
Subreddit: apexlegends
Comment: We don’t talk about paragon 😭😭😭😭 F
--------------------------------------------------
Subreddit: AskReddit
Comment: But I want to buy a safe ocean faring sailboat 😭😭😭😭😭😭
--------------------------------------------------
Subreddit: teenagers
Comment: ya couldn't even put a pc option in😭😭😭whatever I bs'd an answer for ya;)
--------------------------------------------------
Subreddit: hockey
Comment: The Sharks power play is bad hahaha 🤣😂😭😭😭
--------------------------------------------------
Subreddit: AskReddit
Comment: Yep. Definitely don't recommend listening to that alone. 😭😭😭
--------------------------------------------------
Subreddit: freefolk
Comment: Well not in battle anyway. Poor Ed! 😭😭
--------------------------------------------------
Subreddit: gaming
Comment: Ben shwartz? More like Ben ^(i want to die) ***lol Xd 😂😂😂🤪🤪🤪😭😭🤣🤣😫🥚😁😂😂😂***
--------------------------------------------------
Subreddit: teenagers
Comment: I cried when iron man died but I fucking burst out in tears when I saw cap dancing... he finally got his dance after all those years 😭😭 But I feel like they both got what was good. Cap got his happy ending and iron man got to sacrifice himself to save the universe.
--------------------------------------------------
Subreddit: gameofthrones
Comment: Facts lmao imagine spending hours thinking of a theory that the writer don’t give a fuck about 💀💀💀💀🤡🤡
--------------------------------------------------
Subreddit: memes
Comment: I gotta study in ramadan 😭😭😭😭
--------------------------------------------------
Subreddit: MortalKombat
Comment: 😭😭😭😭 Stop crying 🙄
--------------------------------------------------
Subreddit: teenagers
Comment: 😭😭😭my second favorite rapper 😔 but more he was more of an ARTIST than anything
--------------------------------------------------
Subreddit: MortalKombat
Comment: Wtf is going on with pc 😂😂😭😭
--------------------------------------------------
Subreddit: apexlegends
Comment: Lol, Paragon is dead, Apex doesn't even come close.

And now... A moment of silence for our fallen hero of a game.... I'll wait, while you sob... 😭😭😭
--------------------------------------------------
Subreddit: marvelstudios
Comment: **ENDGAME SPOILER**

&gt;!Gonna need some cheeseburgers to work on your Endgame cosplay!!!!&lt; 😭😭😭

(Also, fantastic fucking job, dude!)
--------------------------------------------------
Subreddit: freefolk
Comment: One of the best scenes ever in GoT 😭😭😭😭😭
--------------------------------------------------
Subreddit: teenagers
Comment: You missed my birthday by a little more than 4 months 😭😭😭
--------------------------------------------------
Subreddit: freefolk
Comment: RIP little bear. 😭😭
--------------------------------------------------
Subreddit: dankmemes
Comment: Finally someone who understands how I feel about those people

Edit: Thanks for the likes guys i never had so many likes in my life, yall are awesome 😭😭😭
--------------------------------------------------
Subreddit: gaming
Comment: Hollywood tries to make every live action movie characters realistic, but they don't understand that the characters are loved so much only because they're unrealistic and fun.....😭😭😭😭😭
--------------------------------------------------
Subreddit: teenagers
Comment: 😭😭😭 We are no longer friends
--------------------------------------------------
Subreddit: memes
Comment: this poor kid 😭😭😭
--------------------------------------------------
Subreddit: marvelstudios
Comment: Fk this post and fk the internet.... ppl suk 😭😭.... JK about the post it's  cool, would be funny if it were true to me😢
--------------------------------------------------
Subreddit: memes
Comment: Bitches, I got 4k+ and still only 2,150 karma. Someone help mah ugly ass😭😭😭
--------------------------------------------------
Subreddit: teenagers
Comment: 😭😭 ig u can use the OLD flair at least
--------------------------------------------------
Subreddit: marvelstudios
Comment: Wonderful indeed! The scene between Iron Man and Captain America in Civil War is also amazing. Now can you do the one where Iron man is wearing the gauntlet with all the Infinity Stones on it?

I just don’t want to forget that moment...*sniffs*...*sob*...😭😭😭
--------------------------------------------------
Subreddit: memes
Comment: Oh god this is not a vape he needs it to breathe give him back or he is going to die!!!!!!!!!!!!!!! 😮😮😮😭😭😭
--------------------------------------------------
Subreddit: freefolk
Comment: I’M FUCKN CRYING 😭😭
--------------------------------------------------
Subreddit: memes
Comment: This is so sad😭😭
--------------------------------------------------
Subreddit: unpopularopinion
Comment: there’s actually been kids at my school who have brought sex toys to school-
i’m really surprised the teacher didn’t see a bright neon pink 10 inch goddamn dildo sticking to the table

but yeah that was another thing - their search history and amazon recommendations are gonna be so screwed up 💀💀
--------------------------------------------------
Subreddit: gonewild
Comment: Awww I'm so sorry 😭😭😭 she clearly didn't deserve you then.
--------------------------------------------------
Subreddit: dankmemes
Comment: This was simply beautiful. I'm not crying, you're crying 😢😭😭😭
--------------------------------------------------
Subreddit: marvelstudios
Comment: Damn it man, stop... 😭😭😭😭
--------------------------------------------------
Subreddit: FortNiteBR
Comment: 😭😭😭😭😭 WHY didn't i join in season 3?! That was the best season for forever
--------------------------------------------------
Subreddit: freefolk
Comment: "But melisandre said that arya would close blue eyes"

"Oh for fucks sake, tormund has blue eyes"






😭😭😭
--------------------------------------------------
Subreddit: gameofthrones
Comment: “I didn’t lie!!” 😭😭😭😭
--------------------------------------------------
Subreddit: MortalKombat
Comment: Kitana went from kombo queen in mkx to combo failure in mk11 😭😭
--------------------------------------------------
Subreddit: gonewild
Comment: What if I've got no fucks to give? 😭😭😭
--------------------------------------------------
Subreddit: marvelstudios
Comment: I was 6 when Iron man released. 17 now, I become an adult as this era ends 😭😭😭.
--------------------------------------------------
Subreddit: Market76
Comment: You and me both lol.
I do have a bloodied laser but it's not explosive.  😭😭😭😭
--------------------------------------------------
Subreddit: pics
Comment: Followed! And yea, this year especially. I’m in CT and good god these last few weeks have been cold and gloomy. 😭😭. love the photography!!
--------------------------------------------------
Subreddit: marvelstudios
Comment: Ok knowing this just makes me cry even harder 😭😭
--------------------------------------------------
Subreddit: aww
Comment: Must have that dog 😭😭😭😭
--------------------------------------------------
Subreddit: freefolk
Comment: This was the only scene that got me. I actually whimpered and said, "oh. The dragon." He was comforting momma. 😭😭
--------------------------------------------------
Subreddit: Market76
Comment: 😱 noooooooo!!!! Traitor !!!!!! 😭😭😭😭😭

Jk;) glad you did. What ammo type do you use ?
--------------------------------------------------
Subreddit: relationship_advice
Comment: Ewww lets ostracize someone for doing something I don't understand. Wah wah im insecure 😭😭😭
--------------------------------------------------
Subreddit: marvelstudios
Comment: STOP imma start crying again 😭😭😭
--------------------------------------------------
Subreddit: RoastMe
Comment: Probably never 😭😭😭




Why the fuck is crapitalism so pervasive???
--------------------------------------------------
Subreddit: RoastMe
Comment: Probably never 😭😭😭




Why the fuck is crapitalism so pervasive???
--------------------------------------------------
Subreddit: RoastMe
Comment: Not my NPR!!! 😭😭😭
--------------------------------------------------
Subreddit: news
Comment: Shame I'm really allergic to them 😭😭🤣
--------------------------------------------------
Subreddit: teenagers
Comment: i am iron man 😭😭
--------------------------------------------------
Subreddit: marvelstudios
Comment: Noobmaster😩, hey👋🏻☝️ it’s Thor⚡️ again⤵️. You 👈🏻know🧠, the god🙏🏼 of thunder🌩? Listen🔈 buddy, if you don’t ❌log off⬇️ this game🎮 immediately😤 I will fly🚶🏼‍♂️💨 over to your house🏡, and come 😩👌🏼down⬇️⬇️ to that basement you’re hiding 🤤in and rip 👁👄👁off your arms and shove them up your butt🍑! Oh😮, that’s right➡️, yea just go❗️ cry😭😭 to your father 🤡you little weasel.🐒
--------------------------------------------------
Subreddit: freefolk
Comment: If it makes you feel better, Friki said: "In my others social media people are asking me about Reddit leaks. Do not trust them". I checked his Twitter account and people were writing " Is it true? Jon is going to kill Dany? 😢😭😭  buaaa"
--------------------------------------------------
Subreddit: teenagers
Comment: How u gonna take that L😭😭
--------------------------------------------------
Subreddit: nfl
Comment: Jets fans act like Sam Darnold is next coming of Tom Brady and shit on everyone else 💀💀💀
--------------------------------------------------
Subreddit: pics
Comment: All she "had" was a rich husband. 😭😭😭
--------------------------------------------------
Subreddit: soccer
Comment: Suarez turns into slender man whenever he’s in offside position 💀💀
--------------------------------------------------
Subreddit: MortalKombat
Comment: 😭😭😭😭😭😭😭😭😭😭 I didn’t know you could watch a book LMFAOOOOOO 16 yr olds these days🤣🤣
--------------------------------------------------
Subreddit: ChapoTrapHouse
Comment: Nooo did skelly boi change his pfp 😭😭
--------------------------------------------------
Subreddit: nfl
Comment: I love lions fans. That one pic of the dude with the baby after yall lost to the Vikings had me dying 😭😭
--------------------------------------------------
Subreddit: aww
Comment: Oh my heart !!!😭😭😭😭
--------------------------------------------------
Subreddit: marvelstudios
Comment: Fucking damnit man, I'm crying like a bitch. 😢😢😢


Tony... Steve... Natasha... STEVE MAN, TONY MAN!!!!! It's over, it's over....


Spidey used killer mode, everyone was there, EVERYONE.


Only thing that makes me laugh a little is remembering that "let's do this girls moment" 😂 that was cringy af.


And now I'm sad again. 😭😭😭😭😭😭


It's been great fellas, see you in the next one, though we know, it will never be the same.
--------------------------------------------------
Subreddit: marvelstudios
Comment: Absolutely, it was meant for them, doesn't take away that it felt funny, powerful but funny.


And also didn't take away anything, since we know... who saved us.... *sniff* 😭😭😭😭


Imma go cry in my corner again.
--------------------------------------------------
Subreddit: aww
Comment: I love him 😭😭😭😭
--------------------------------------------------
Subreddit: aww
Comment: I don't know you but I love you for being so awesome. You make humanity proud. God bless you and the dogo 😭😭😭
--------------------------------------------------
Subreddit: hockey
Comment: It’s really hard to watch. especially waiting 10 days for more hockey. The canes are great and I will 1000% root for them, just want to win at least one game. At least they got further than JT. Right ?! Right? 😭😭😭😩😩😩
--------------------------------------------------
Subreddit: hockey
Comment: Man i didn’t even notice that she sounded like a kid, until i went to this thread.

Now that’s all i hear💀💀
--------------------------------------------------
Subreddit: MortalKombat
Comment: You soft as fuck 😭😭🤣🤣 I gives no fucks bout you or yo lil reddit feinds
--------------------------------------------------
Subreddit: MortalKombat
Comment: Get yo soy boy ass beat in the streets on foenem😭😭😭
--------------------------------------------------
Subreddit: MortalKombat
Comment: Slide north side minneosta short boa well show you how it’s bussin outside 👎🏽✌🏽😭😭😭😭
--------------------------------------------------
Subreddit: MortalKombat
Comment: You in the suburbs fuck off a nigga dick capa 😭😭
--------------------------------------------------
Subreddit: aww
Comment: I just said, "oh my God calhoun" 😭😭😭
--------------------------------------------------
Subreddit: MortalKombat
Comment: Sonya is OP 😭😭😱
--------------------------------------------------
Subreddit: apexlegends
Comment: I hope Respawn implements some rank-based matchmaking system ASAP! 😭😭😭
--------------------------------------------------
Subreddit: MortalKombat
Comment: Or how about when past Scorpion holds present Scorpion as he dies in his arms and the screen fades out and soft music plays 😭😭😭😭😢😢😢😭
--------------------------------------------------
Subreddit: MortalKombat
Comment: Dannnnng just got goosebumps...and Raiden apologizing for being an asshole 😕😭😭
--------------------------------------------------
Subreddit: FortNiteBR
Comment: Lost my shit 😭😭😭😂😂😂
--------------------------------------------------
Subreddit: MortalKombat
Comment: 😭😭😭😭

This hurts me.
--------------------------------------------------
Subreddit: SquaredCircle
Comment: "Screw you Pepsi boy💀💀"
--------------------------------------------------
Subreddit: gaming
Comment: Very first PC game my folks bought me back in the day 😎😭😭
--------------------------------------------------
Subreddit: aww
Comment: I just moved away for college for the first time and I can’t wait for the quarter to be over so I can cuddle the heck out my pupper 😭😭😩😩. She my screensaver cuz I miss her so much and I need to see her everyday. Also your pup looks like that quiet ‘awoo’ meme.
--------------------------------------------------
Subreddit: RoastMe
Comment: that roast was so good i’m contemplating whether or not you meant it 💀💀
--------------------------------------------------
Subreddit: MortalKombat
Comment: I beat him by using an increase fire damage konsumable and a fire fist konsumable but I forgot to do a fatality so I have to do it again. 😭😭😭😭
--------------------------------------------------
Subreddit: MortalKombat
Comment: Oh my God that car analogy 😂😂💀💀💀
--------------------------------------------------
Subreddit: MortalKombat
Comment: You’re 16 and infatuated with me 😭😭😭😭 go get a job dude
--------------------------------------------------
Subreddit: apexlegends
Comment: Ikr, why can't bullets be hitscan irl 😭😭😭
--------------------------------------------------
Subreddit: Pikabu
Comment: 😭😭😭 Переведите это на английский. Пусть читают иноземцы про то, какой ценой наши освобождали европу от нацистов
--------------------------------------------------
Subreddit: aww
Comment: Sweet soft face 😭😭😭❤️❤️❤️
--------------------------------------------------
Subreddit: FortNiteBR
Comment: Its my Block!!! EPIC GAMES... please update 😭😭😭
--------------------------------------------------
Subreddit: wallstreetbets
Comment: DIS NOOOO THEY ARE RAPE ING MICKY

STOPPPPPP

PLEASEEEEEEEE

😭😭😭😭😭😭
--------------------------------------------------
Subreddit: wallstreetbets
Comment: APPLE YOUR OUR ONLY HOPE USA STAY SOILD 🍏🍏🍏🍏🍏🍏  THE BEARS ARE BACK 🐻🐻🐻😭😭😭  THERE ASSHOLE SKINS ARE HARDEN FROM ALL THE POUNDING AND THEY MAD AS FUCK NOW
--------------------------------------------------
Subreddit: ChapoTrapHouse
Comment: bro im sorry we lowered your karma score 😭😭😭😭
--------------------------------------------------
Subreddit: MortalKombat
Comment: Jesus Christ will people stop bullying Frost! It’s bad enough she gets it from everyone in the game. 😭😭
--------------------------------------------------
Subreddit: wallstreetbets
Comment: Ok guys time to delete the app


See ya Friday.

😥😥😥😭😭
--------------------------------------------------
Subreddit: apexlegends
Comment: Its not that easy... 😭😭😭
--------------------------------------------------
Subreddit: wallstreetbets
Comment: 😥😥😥😥😥😭😭😭😭😭😭😭🐻🐻🐻🐻🐻 why

WHY MUST I CRYYYYYY
--------------------------------------------------
Subreddit: FortNiteBR
Comment: “ePiC pLz ReLeAsE sTeRLiNg I wAs OnLy 50 vBuCkS aWaY” 😩😩😭😭
--------------------------------------------------
Subreddit: relationship_advice
Comment: 💀💀💀 you right. I’m bout to pack up all my shit and head back to MI
--------------------------------------------------
Subreddit: pics
Comment: I’m saying no fucking way to the article which likens vaccinations to nazi eugenics😭😭
--------------------------------------------------
Subreddit: gonewild
Comment: Omg thank you 😭😭😭💞💞💞
--------------------------------------------------
Subreddit: gonewild
Comment: I love my fans 😭😭💞💞 you are too kind, wow. 💋
--------------------------------------------------
Subreddit: gonewild
Comment: The only complaint I have about your tattoos is that I haven't seen them earlier!! They're absolutely gorgeous 😭😭
--------------------------------------------------
Subreddit: wallstreetbets
Comment: I have 1 more week. My calls got fucking crushed by IV, they were up 180% around 86.50 yesterday and now they’re at 7% 💀💀💀 when it hit 90 today I was up $3k, and thought it broke all resistance and would short squeeze. Now I’m up a measly $53
--------------------------------------------------
Subreddit: RoastMe
Comment: that sounds like a rap. could i use that for my soundcloud account? i’m an aspiring rapper, and really want followers 😭😭😭

-me, roasting myself because i look very basic in this picture; aka the point of the post
--------------------------------------------------
Subreddit: ChapoTrapHouse
Comment: If only more people Pokemon Went to the polls... 😭😭😭

## Serious-Tone Reddit Comment Classification

Serious tone is defined as the absence of emojis in comments, particularly within politics and news-related subreddits.

This form of communication relies on textual language alone and reflects a more formal register, where emotional expression is minimized. In contrast to emoji-based discourse, serious comments prioritize clarity, argumentation, and informational content.

This category serves as a baseline for comparison, allowing the analysis to examine how the presence or absence of emojis influences tone, emotional intensity, and communicative style.

#### Reddit Classification for Serious-Tone Comments

In [46]:
import pandas as pd
import re

# load original kaggle dataset
df = pd.read_csv("kaggle_RC_2019-05.csv")


# filter politics/news
def is_politics_news(subreddit):
    subreddit = str(subreddit).lower()
    return any(word in subreddit for word in ["politics", "news", "worldnews"])


# check no emojis
def has_no_emoji(text):
    if pd.isna(text):
        return False
    return not bool(re.search(r'💀|😭', text))

# filter dataset
serious_comments = df[
    df["subreddit"].apply(is_politics_news) &
    df["body"].apply(has_no_emoji)
]

# print sample
print("Sample of Serious Tone:")

for i, row in serious_comments.head(20).iterrows():  # only first 20
    print(f"Subreddit: {row['subreddit']}")
    print(f"Comment: {row['body']}")
    print("-" * 50)

# save to CSV
serious_comments.to_csv("politics_news_no_emoji.csv", index=False)

print("\nSaved to politics_news_no_emoji.csv")
print("Total rows:", len(serious_comments))

Sample of Serious Tone:
Subreddit: news
Comment: You know we have laws against that currently correct? Or are you just willfully ignorant of gun laws in the US.
--------------------------------------------------
Subreddit: politics
Comment: Yes, there is a difference between gentle suppression and hard suppression.  Neither are good things.
--------------------------------------------------
Subreddit: worldnews
Comment: How many millions have to suffer and die for them to feel any of that pain though?
--------------------------------------------------
Subreddit: news
Comment: No, not really at all. It happens too often but it's ridiculous to pretend that applies to everyone.
--------------------------------------------------
Subreddit: news
Comment: This is disgusting every week
--------------------------------------------------
Subreddit: worldnews
Comment: Trump's administration is lying on Fox news? I can't believe it!
--------------------------------------------------
Subreddit: worldnews
Comment: &gt; Industry in China is still deeply entwined with the state. The notion that China just suddenly became capitalist is pervasive and misguided.

That's called state capitalism with a centralised planning system not socialism.

&gt;Socialism refers to state ownership of the means of production

No, the workers own it, not the state. What usually happens is that the state assumes control over the means of production via authoritarianism.

&gt;The Chinese government and communist party directly run the economy

CCP is about as Communist as the Democrat People's Republic of Korea (North Korea) is Democratic.

&gt;China is actually less socialist than Nordic model countries in the realm of wealth redistribution and tax rates.

Social democratic societies such as the Nordic Model operate under a capitalist framework. They just have generous welfare nets.

&gt;Perhaps you can't actually call China socialist, perhaps they're something new and unique.

Not even Chinese people consider their government socialist. Words have meanings.

Even under a "state owned system", the wealth needs to be redistributed and funneled into public welfare systems. The state should also not profit off of the enterprises and industries they own.

To put it simply, you are incorrect in your assessment. China is a ruthless, authoritarian capitalist society that will break any rules needed to get ahead. That's why they are where they are in such a short span of time.
--------------------------------------------------
Subreddit: worldnews
Comment: Meanwhile in Ontario our government just cancelled funding to plant 50 million trees.

Makes you wonder sometimes.

https://www.google.com/amp/s/www.cbc.ca/amp/1.5110282
--------------------------------------------------
Subreddit: worldnews
Comment: Sorry. I don't speak with people who talk like children.
--------------------------------------------------
Subreddit: politics
Comment: He also got married, and they filed jointly for 2018. So his husband's income as a teacher should be in the 2018 number, but not the 2017 number.
--------------------------------------------------
Subreddit: news
Comment: The movie is completely different than the comics though.
--------------------------------------------------
Subreddit: news
Comment: Ban guns ... is the most obvious. (Let's see how many downvotes I amass, and then you'll realize why this keeps happening here.)
--------------------------------------------------
Subreddit: politics
Comment: So you think we can just tell people they no longer have the right to express themselves?
--------------------------------------------------
Subreddit: news
Comment: &gt; If you remove suicides and gang violence our "gun violence epidemic" suddenly disappears entirely.

Mass-shootings in Universities are not by gangs, nor suicide cases (despite shooters routinely taking their own lives afterwards). It is something that just doesn't happen on the scale it does in America, and a large factor in that is the ease of gun access.

6 people a year (wherever you pulled that stat) is 6 too many.
--------------------------------------------------
Subreddit: politics
Comment: ITT, lots of people without jobs complaining.
--------------------------------------------------
Subreddit: politics
Comment: "You boys wanna shovel some coal?"
--------------------------------------------------
Subreddit: news
Comment: The character 令 does bear a meaning similar to "beautiful" in classical Chinese. Here are some examples I thought of:

&gt;子曰：“巧言令色，鲜矣仁。”

&gt;The Master said, "Fine words and an insinuating appearance are seldom associated with true virtue."

This is from [*Analacts*](https://en.m.wikipedia.org/wiki/Analects).

Source: [Wikisource](https://en.m.wikisource.org/wiki/Confucian_Analects/I).

&gt;夫何瑰逸之令姿，独旷世以秀群。

This is from *The Rhapsody of Leisured Emotions* (闲情赋) by [Tao Yuanming](https://en.m.wikipedia.org/wiki/Tao_Yuanming). I cannot find d an "official" translation so here's my stab at it:

&gt;Oh, such an elegant posture, standing out from the mundane world.

On top of the 2 examples, the character 令 is used in honorifics in modern Chinese.
--------------------------------------------------
Subreddit: worldnews
Comment: Weird, considering private ownership of firearms is illegal. Have they tried background checks and magazine bans? A 3 day waiting period, perhaps?
--------------------------------------------------
Subreddit: news
Comment: retribution for rejecting a state and losing multiple wars trying to conquer Israel and kill and/or oust the Jews?  Interesting thought but not really.
--------------------------------------------------
Subreddit: worldnews
Comment: I don't understand what you mean by twisting. What do you want me to do? Really, i try my best to showcase what is going on. You know what forget it, you are what i sadly call a lost case. If you say that the US has propaganda and everything, every goverment has it, and it doesn't exclude the leftists goverment.
--------------------------------------------------

Saved to politics_news_no_emoji.csv
Total rows: 74996

## Full Uploaded And Organized Dataset + Dashboard

The final dataset integrates multiple processed data sources into a single, structured file for analysis.

It combines:
- Emoji-containing comments (💀, 😭) from the cleaned dataset
- Emoji-free comments from politics and news subreddits in the original dataset

Each comment is enriched with additional features, including:
- Subreddit (source community)
- Category (e.g., sports, gaming, memes, politics)
- Emoji type (skull, crying, mixed, or none)
- Emoji intensity (single or repeated)
- Tone classification (casual, intensified emotion, or serious)

This structured dataset enables direct comparison between different communication styles, allowing the analysis to examine how emoji use, emotional intensity, and topic context interact in online discourse.

By organizing the data in this way, the project moves beyond simple filtering and creates a comprehensive framework for both quantitative and qualitative linguistic analysis.

Dashboard:

This efficiently classifies and allows to check emoji specific data, as well as specific Reddit emoji data being used for this project.

#### Intall Necessary Packages

In [ ]:
!pip install ipywidgets

#### Data Preperation

In [47]:
import pandas as pd

# load original dataset
df = pd.read_csv("kaggle_RC_2019-05.csv")

# emoji type
def detect_emoji_type(text):
    text = str(text)
    if "😭" in text:
        return "crying"
    elif "💀" in text:
        return "skull"
    else:
        return "none"

df["emoji_type"] = df["body"].apply(detect_emoji_type)


# emoji intensity
def emoji_intensity(text):
    text = str(text)
    return text.count("😭") + text.count("💀")

df["emoji_intensity"] = df["body"].apply(emoji_intensity)


# category
def categorize_subreddit(sub):
    sub = str(sub).lower()

    if any(x in sub for x in ["nba", "nfl", "soccer", "hockey"]):
        return "sports"
    elif any(x in sub for x in ["gaming", "xbox", "pcgaming"]):
        return "gaming"
    elif any(x in sub for x in ["memes", "funny"]):
        return "memes"
    elif any(x in sub for x in ["politics", "news"]):
        return "politics"
    else:
        return "other"

df["category"] = df["subreddit"].apply(categorize_subreddit)


# tone
def classify_tone(row):
    if row["category"] == "politics" and row["emoji_type"] == "none":
        return "serious"
    else:
        return "informal"

df["tone"] = df.apply(classify_tone, axis=1)


# final dataset
final_df = df.copy()

# save it
final_df.to_csv("FINAL_FULL_DATASET.csv", index=False)

print("FINAL DATASET CREATED")

FINAL DATASET CREATED

In [48]:
import pandas as pd

df = pd.read_csv("FINAL_FULL_DATASET.csv")
print(df.columns)

files.download("FINAL_FULL_DATASET.csv")

Index(['subreddit', 'body', 'controversiality', 'score', 'emoji_type',
       'emoji_intensity', 'category', 'tone'],
      dtype='object')

#### Dashboard Interactive Button System

In [51]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output

df = pd.read_csv("FINAL_FULL_DATASET.csv")

print("Columns:", df.columns)
print("Total rows:", len(df))

output = widgets.Output()

def category_data(emoji):
    sports_terms = ["nba", "nfl", "soccer", "basketball", "football", "hockey"]
    gaming_terms = ["gaming", "ps5", "xbox", "pcgaming"]
    meme_terms = ["meme", "memes", "funny", "dankmemes"]

    def match_category(sub):
        sub = str(sub).lower()
        return (
            any(x in sub for x in sports_terms) or
            any(x in sub for x in gaming_terms) or
            any(x in sub for x in meme_terms)
        )

    return df[
        (df["emoji_type"] == emoji) &
        (df["subreddit"].apply(match_category))
    ][["subreddit", "body", "category", "emoji_intensity"]]

def full_data(emoji):
    return df[df["emoji_type"] == emoji][
        ["subreddit", "body", "category", "emoji_intensity"]
    ]

def serious_full():
    return df[df["emoji_type"] == "none"][
        ["subreddit", "body", "category"]
    ]

def serious_news_politics():
    terms = ["news", "politics"]
    return df[
        (df["emoji_type"] == "none") &
        (df["subreddit"].str.lower().apply(lambda x: any(t in x for t in terms)))
    ][["subreddit", "body", "category"]]

def show_table(data):
    with output:
        clear_output()
        print(f"Total rows: {len(data)}")
        display(data)

def emoji_menu(emoji_name):
    btn_full = widgets.Button(description="📊 Full Data")
    btn_cat = widgets.Button(description="🎯 Sports/Gaming/Memes")

    btn_full.on_click(lambda x: show_table(full_data(emoji_name)))
    btn_cat.on_click(lambda x: show_table(category_data(emoji_name)))

    return widgets.VBox([btn_full, btn_cat])

def serious_menu():
    btn_full = widgets.Button(description="📊 Full Data")
    btn_np = widgets.Button(description="📰 News/Politics")

    btn_full.on_click(lambda x: show_table(serious_full()))
    btn_np.on_click(lambda x: show_table(serious_news_politics()))

    return widgets.VBox([btn_full, btn_np])

btn_cry = widgets.Button(description="😭 Crying Emoji")
btn_skull = widgets.Button(description="💀 Skull Emoji")
btn_serious = widgets.Button(description="📰 Serious Tone")

def click_cry(b):
    with output:
        clear_output()
        display(emoji_menu("crying"))

def click_skull(b):
    with output:
        clear_output()
        display(emoji_menu("skull"))

def click_serious(b):
    with output:
        clear_output()
        display(serious_menu())

btn_cry.on_click(click_cry)
btn_skull.on_click(click_skull)
btn_serious.on_click(click_serious)

display(widgets.HBox([btn_cry, btn_skull, btn_serious]))
display(output)

Columns: Index(['subreddit', 'body', 'controversiality', 'score', 'emoji_type',
       'emoji_intensity', 'category', 'tone'],
      dtype='object')
Total rows: 1000000

HBox(children=(Button(description='😭 Crying Emoji', style=ButtonStyle()), Button(description='💀 Skull Emoji', …

Output()